// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// vp11
NumericVector vp11(NumericVector vw, double t, double lambda1, double lambda0);
RcppExport SEXP smam_vp11(SEXP vwSEXP, SEXP tSEXP, SEXP lambda1SEXP, SEXP lambda0SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type vw(vwSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< double >::type lambda0(lambda0SEXP);
    __result = Rcpp::wrap(vp11(vw, t, lambda1, lambda0));
    return __result;
END_RCPP
}
// vp10
NumericVector vp10(NumericVector vw, double t, double lambda1, double lambda0);
RcppExport SEXP smam_vp10(SEXP vwSEXP, SEXP tSEXP, SEXP lambda1SEXP, SEXP lambda0SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type vw(vwSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< double >::type lambda0(lambda0SEXP);
    __result = Rcpp::wrap(vp10(vw, t, lambda1, lambda0));
    return __result;
END_RCPP
}
// vp00
NumericVector vp00(NumericVector vw, double t, double lambda1, double lambda0);
RcppExport SEXP smam_vp00(SEXP vwSEXP, SEXP tSEXP, SEXP lambda1SEXP, SEXP lambda0SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type vw(vwSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< double >::type lambda0(lambda0SEXP);
    __result = Rcpp::wrap(vp00(vw, t, lambda1, lambda0));
    return __result;
END_RCPP
}
// vp01
NumericVector vp01(NumericVector vw, double t, double lambda1, double lambda0);
RcppExport SEXP smam_vp01(SEXP vwSEXP, SEXP tSEXP, SEXP lambda1SEXP, SEXP lambda0SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type vw(vwSEXP);
    Rcpp::traits::input_parameter< double >::type t(tSEXP);
    Rcpp::traits::input_parameter< double >::type lambda1(lambda1SEXP);
    Rcpp::traits::input_parameter< double >::type lambda0(lambda0SEXP);
    __result = Rcpp::wrap(vp01(vw, t, lambda1, lambda0));
    return __result;
END_RCPP
}
// h11
NumericVector h11(NumericMatrix x, NumericVector t, NumericVector theta, NumericVector integrControl);
RcppExport SEXP smam_h11(SEXP xSEXP, SEXP tSEXP, SEXP thetaSEXP, SEXP integrControlSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type integrControl(integrControlSEXP);
    __result = Rcpp::wrap(h11(x, t, theta, integrControl));
    return __result;
END_RCPP
}
// h10
NumericVector h10(NumericMatrix x, NumericVector t, NumericVector theta, NumericVector integrControl);
RcppExport SEXP smam_h10(SEXP xSEXP, SEXP tSEXP, SEXP thetaSEXP, SEXP integrControlSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type integrControl(integrControlSEXP);
    __result = Rcpp::wrap(h10(x, t, theta, integrControl));
    return __result;
END_RCPP
}
// h00
NumericVector h00(NumericMatrix x, NumericVector t, NumericVector theta, NumericVector integrControl);
RcppExport SEXP smam_h00(SEXP xSEXP, SEXP tSEXP, SEXP thetaSEXP, SEXP integrControlSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type integrControl(integrControlSEXP);
    __result = Rcpp::wrap(h00(x, t, theta, integrControl));
    return __result;
END_RCPP
}
// h01
NumericVector h01(NumericMatrix x, NumericVector t, NumericVector theta, NumericVector integrControl);
RcppExport SEXP smam_h01(SEXP xSEXP, SEXP tSEXP, SEXP thetaSEXP, SEXP integrControlSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type t(tSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type integrControl(integrControlSEXP);
    __result = Rcpp::wrap(h01(x, t, theta, integrControl));
    return __result;
END_RCPP
}
// ncllk_m1_inc
double ncllk_m1_inc(NumericVector& theta, NumericMatrix& data, NumericVector& integrControl, LogicalVector& logtr);
RcppExport SEXP smam_ncllk_m1_inc(SEXP thetaSEXP, SEXP dataSEXP, SEXP integrControlSEXP, SEXP logtrSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type integrControl(integrControlSEXP);
    Rcpp::traits::input_parameter< LogicalVector& >::type logtr(logtrSEXP);
    __result = Rcpp::wrap(ncllk_m1_inc(theta, data, integrControl, logtr));
    return __result;
END_RCPP
}
// nllk_inc
double nllk_inc(NumericVector& theta, NumericMatrix& data, NumericVector& integrControl, LogicalVector& logtr);
RcppExport SEXP smam_nllk_inc(SEXP thetaSEXP, SEXP dataSEXP, SEXP integrControlSEXP, SEXP logtrSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< NumericVector& >::type integrControl(integrControlSEXP);
    Rcpp::traits::input_parameter< LogicalVector& >::type logtr(logtrSEXP);
    __result = Rcpp::wrap(nllk_inc(theta, data, integrControl, logtr));
    return __result;
END_RCPP
}
