# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vp11 <- function(vw, t, lambda1, lambda0) {
    .Call('smam_vp11', PACKAGE = 'smam', vw, t, lambda1, lambda0)
}

vp10 <- function(vw, t, lambda1, lambda0) {
    .Call('smam_vp10', PACKAGE = 'smam', vw, t, lambda1, lambda0)
}

vp00 <- function(vw, t, lambda1, lambda0) {
    .Call('smam_vp00', PACKAGE = 'smam', vw, t, lambda1, lambda0)
}

vp01 <- function(vw, t, lambda1, lambda0) {
    .Call('smam_vp01', PACKAGE = 'smam', vw, t, lambda1, lambda0)
}

h11 <- function(x, t, theta, integrControl) {
    .Call('smam_h11', PACKAGE = 'smam', x, t, theta, integrControl)
}

h10 <- function(x, t, theta, integrControl) {
    .Call('smam_h10', PACKAGE = 'smam', x, t, theta, integrControl)
}

h00 <- function(x, t, theta, integrControl) {
    .Call('smam_h00', PACKAGE = 'smam', x, t, theta, integrControl)
}

h01 <- function(x, t, theta, integrControl) {
    .Call('smam_h01', PACKAGE = 'smam', x, t, theta, integrControl)
}

ncllk_m1_inc <- function(theta, data, integrControl, logtr) {
    .Call('smam_ncllk_m1_inc', PACKAGE = 'smam', theta, data, integrControl, logtr)
}

nllk_inc <- function(theta, data, integrControl, logtr) {
    .Call('smam_nllk_inc', PACKAGE = 'smam', theta, data, integrControl, logtr)
}

